# Generated by Django 6.0.6 on 2026-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('REQUEST_RECEIVED', 'Request Received'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('SYSTEM', 'System'), ('TRANSACTION_COMPLETED', 'Transaction Completed')], default='SYSTEM', max_length=30),
        ),
    ]
