# Generated by Django 6.0.6 on 2026-07-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availability_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=15),
        ),
    ]
